global:
  scrape_interval: 15s

scrape_configs:

# Prometheus host itself
- job_name: prometheus-host
  static_configs:
    - targets: ["{prometheus-ip}:9100"]

# Jenkins host
- job_name: jenkins-host
  static_configs:
    - targets: ["{jenkins-ip}:9100"]

# Jenkins application
- job_name: jenkins
  metrics_path: /prometheus
  static_configs:
    - targets: ["{jenkins-ip}:8080"]

# Kubernetes Node Exporters
- job_name: k8s-workers
  static_configs:
    - targets:
        - "{worker1-ip}:9100"
        - "{worker2-ip}:9100"

# Kubernetes kubelet / cAdvisor
- job_name: kubelet
  scheme: https
  static_configs:
    - targets:
        - "{master-ip}:10250"
        - "{worker1-ip}:10250"
        - "{worker2-ip}:10250"
  tls_config:
    insecure_skip_verify: true
  bearer_token_file: /etc/prometheus/k8s-token
  metrics_path: /metrics/cadvisor
